version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
    volumes:
      - uploads:/app/uploads
      - data:/app/data

volumes:
  uploads:
  data: